Update archx
Refined ArchX > Install > Apps > wine: Added installation steps for .NET implementation (wine-mono) and Vulkan implementation (dxvk-bin)

removed picom installed as default, because not in all gpu work nice, like on old laptops.

if you want it do:
  archx > install > apps > picom

diff --git a/.local/share/bin/cpbin b/.local/share/bin/cpbin
--- a/.local/share/bin/cpbin
+++ b/.local/share/bin/cpbin
@@ -1,26 +1,36 @@
 #!/bin/bash
-# Copy binaries with deps in a folder
-if [[ "$#" -ne 2 ]]; then
-    echo "Usage: cpbin <command> <path>"
-    return 1
+# Copy binaries with dependencies to a specified folder
+usage() {
+    echo "Usage: $0 <command> <path>"
+    exit 1
+}
+if [[ "$#" -lt 1 ]]; then
+    usage
 fi
-target_path="$2"
-program=$(type -a "$1" | grep -o '/[^ ]*$')
+command="$1"
+target_path="${2:-$(pwd)}"
+program=$(type -p "$command")
+if [[ -z "$program" ]]; then
+    echo "Error: Command '$command' not found."
+    exit 1
+fi
 copy_to() {
-    source="$1"
-    destination="$2"
+    local source="$1"
+    local destination="$2"
     sudo mkdir -p "$destination"
-    echo "Coping $source to $destination"
+    echo "Copying $source to $destination"
     sudo cp "$source" "$destination"
 }
 copy_to "$program" "$target_path/bin"
 copy_to "$program" "$target_path/usr/bin"
-echo "Finding and moving dependencies of $program..."
+echo "Finding and copying dependencies of $program..."
 while IFS= read -r dep; do
-    destination="$target_path$(dirname "$dep")"
-    copy_to "$dep" "$destination"
+    if [[ -f "$dep" ]]; then
+        destination="$target_path$(dirname "$dep")"
+        copy_to "$dep" "$destination"
+    fi
 done < <(ldd "$program" | awk '/=>/{print $(NF-1)}')
 sudo cp -r "$target_path/usr/lib" "$target_path/lib"
 sudo cp -r "$target_path/usr/lib64" "$target_path/lib64"
-echo "Coping operation completed successfully."
-echo -e "You can chroot in it with \"sudo chroot "$target_path"\""
+echo "Copy operation completed successfully."
+echo -e "You can chroot into it with: sudo chroot \"$target_path\""
